name             'selinux_policy'
maintainer       'Chef Software, Inc.'
maintainer_email 'cookbooks@chef.io'
license          'Apache-2.0'
description      'Manages SELinux policy components'
source_url       'https://github.com/sous-chefs/selinux_policy'
issues_url       'https://github.com/sous-chefs/selinux_policy/issues'
chef_version     '>= 13.0'
version          '2.4.3'

supports 'redhat'
supports 'centos'
supports 'fedora'
