name             'selinux_policy'
maintainer       'Sous Chefs'
maintainer_email 'help@sous-chefs.org'
license          'Apache-2.0'
description      'Manages SELinux policy components'
source_url       'https://github.com/sous-chefs/selinux_policy'
issues_url       'https://github.com/sous-chefs/selinux_policy/issues'
chef_version     '>= 13.0'
version          '2.4.1'

supports 'redhat'
supports 'centos'
supports 'fedora'
supports 'ubuntu'
supports 'debian'
supports 'amazon'
